env:
  matrix:
    secure: hCJRCZHhLAXMOmKuML2Wi/1ydvINtIZj3SCYoPy/XYhypKdgzkgN4I8ph2lb187dit9yyFlheaSvyB33mjYEWzQKwNFoJynDbVoIRWU6//XVE9cD2Tff4fC61EYrOtl/tNQlv23f6VzvwugflPTVGg6Ged0y4L1QS8BL9Td6qwMUtlcM946EHmDy8gf6OrDLgS0KN/N0uRk7qzlRihNuR/yQKvAjcJq71fSj0pTSjo4986t/s+e1lvd8hz8h3pWUuqYHkl0Xk1EWTnrXt2YHwUptisVNSGKxkot0oKPUsFvmu2X/IfOSg9s3eVmEavYArfoBEQ/yBZh3sYvaA6sebMlcFOsKUsxt288jrASGD2wqDXEbc+U31XqXnzAWabf2j0wS/H+I8yZx85TP4FG7nEeoeWJpluF5Y1tN56Y+inUjLoNtIRi1I9v4paPuPg9Zf5x1FVuPGeuTAEg9aBbqLfJuAfEbd4u3QvGDGy+zrTT8xqgEk7vcakIILP9of9tdYQ3rowo+heVv6Um+xLLPIMZNvlEqolmIHskAJxqKjbuw5jNTFYX06s0vNSJkikgjYDRFtc0alzkt/6MplirW5GhoFuHcYY8uRyzGrS1limJXOmCY/addm12qu/qFJYkZbodr48MDG30F3izS2utWcJX7AKP5uMocALmVNyeNh00=

sudo: required
services:
  - docker

dist: xenial

go:
  - "1.12.x"
language: go

script:
  - ./build.sh
